import { CONTRACT } from "./abi";
export const TOKEN_CONTRACT_ABI = CONTRACT.TOKEN.abi;
export const TOKEN_CONTRACT_ADDRESS = CONTRACT.TOKEN.address;
export const EXCHANGE_CONTRACT_ABI = CONTRACT.EXCHANGE.abi;
export const EXCHANGE_CONTRACT_ADDRESS = CONTRACT.EXCHANGE.address;
